name: CausalPy
channels:
  - conda-forge
dependencies:
  - arviz>=0.14.0
  - graphviz
  - make
  - ipython!=8.7.0
  - matplotlib>=3.5.3
  - numpy
  - pandas
  - patsy
  - pre-commit
  - pymc>=5.15.1
  - scikit-learn>=1
  - scipy
  - seaborn>=0.11.2
  - statsmodels
  - xarray>=v2022.11.0
  - pymc-extras>=0.3.0
  - pymc-bart
  - python>=3.12
  - pip
  - "marimo[mcp]"
