name: "PR Issue Label Sync"

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Sync labels from closing issues
        uses: williambdean/closing-labels@7a4384e0e725b80eee0142265d36c1332fda5f7a # v0.0.6
        with:
          exclude: "help wanted,good first issue"
          respect_unlabeled: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
